server:
  port: 5000

external:
  product-service:
    base-url: http://localhost:3001

resilience4j.circuitbreaker:
  instances:
    similarProductsCircuitBreaker:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfState: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
